#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/shreyash/develop/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/shreyash/Documents/Uniclubb"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/shreyash/Documents/Uniclubb/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/shreyash/Documents/Uniclubb/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=2.0.0"
export "FLUTTER_BUILD_NUMBER=2"
export "DART_DEFINES=U1VQQUJBU0VfVVJMPWh0dHBzOi8vdm16Z3NjamJqa3h6bXFyYnBscmQuc3VwYWJhc2UuY28=,U1VQQUJBU0VfQU5PTl9LRVk9c2JfcHVibGlzaGFibGVfTEx3NlhBY2V0el9JNlp0dldTMVRqQV9ZNlY2OGo3ZA==,QVVUSF9SRURJUkVDVD1pby5zdXBhYmFzZS51bmljbHViOi8vbG9naW4tY2FsbGJhY2s=,QUlfRU5BQkxFRD10cnVl,RkxVVFRFUl9WRVJTSU9OPTMuNDQuOA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049MDU4ZTBhZjJjMg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049MGNkNjEwNzE3Yg==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/shreyash/Documents/Uniclubb/.dart_tool/package_config.json"
